// echo-core.js — Canonical Echo engine bundle (phase 1 — file capture).
// Source: extracted from TMPL_IL_weekday.html, which is byte-identical with TMPL_CL_sat,
// TMPL_IL_sat, TMPL_CL_sun, TMPL_IL_sun (verified by md5 across all 22 shared identifiers,
// 2026-06-10). NOT yet wired in — templates currently still inline these functions.
// Phase 2 (after #4 device-verification): replace inline copies in the 5 propagated templates
// with <script src="../echo-core.js"></script>. CL_weekday and ask.html each need their own
// catch-up first — see SKILL-echo-behaviour.
//
// Required from the embedding page (must be declared BEFORE this script if/when wired in):
//   const CHAR  = CHARS[CHILD];      // character definition (key, voiceName, etc.)
//   let   OPENAI_KEY = ...;          // user's OpenAI key or null
//   function updateVoicePill(){...}  // refreshes the voice-mode pill on 401
// Engine config constants and engine state are owned by this file (declared below).
//
// Do NOT edit this file directly when reproducing a behaviour change across templates —
// change CL_weekday + propagate the bundle, then re-extract here.

// ── engine config ────────────────────────────────────────────────────────────
const OAI_TTS_MODEL='gpt-4o-mini-tts'; // newest, most natural, streaming. Flip to 'tts-1' (fastest) or 'tts-1-hd' (previous) if your account rejects it.
const CUE_RGB={joke:'251,146,60',watch:'6,182,212',try:'168,85,247',check:'34,197,94',notice:'234,179,8',probe:'251,191,36',guess:'20,184,166'};

// ── engine state (top-level lets that engine functions mutate) ───────────────
let _oaiController=null, _oaiAudio=null, _oaiObjectUrl=null;
let _currentUtt=null, _speechGen=0;            // ghost-kill: generation counter + active utterance ref
let _streamCancel=null;
let _onOnset=null;                              // fired the instant audio actually begins

// ── engine functions (dependency-ordered) ────────────────────────────────────

function _fakeAmp(t){return .3+.6*Math.abs(Math.sin(t*2.1))*(.55+.45*Math.sin(t*.73+1.7))*(.7+.3*Math.sin(t*5.3));}

function _waveFrame(cx,W,H,rgb,t,amp){cx.clearRect(0,0,W,H);const g=cx.createLinearGradient(0,0,W,0);g.addColorStop(0,'rgba('+rgb+',0)');g.addColorStop(.5,'rgba('+rgb+',.9)');g.addColorStop(1,'rgba('+rgb+',0)');cx.strokeStyle=g;cx.lineWidth=1.8;cx.shadowBlur=5;cx.shadowColor='rgba('+rgb+',.7)';cx.beginPath();const a=amp*(H/2-2);for(let x=0;x<W;x++){const env=Math.sin(x/W*Math.PI);const y=H/2+Math.sin(x/W*Math.PI*6+t*7)*a*env;x===0?cx.moveTo(x,y):cx.lineTo(x,y);}cx.stroke();cx.shadowBlur=0;}

function _vizStop(){if(_vizAF){cancelAnimationFrame(_vizAF);_vizAF=null;}document.querySelectorAll('.echo-viz.active').forEach(v=>{v.classList.remove('active');const o=v.querySelector('.viz-orb');if(o)o.classList.remove('pulse');});}

function _drawIdleViz(viz,cx,W,H,orb,rgb){rgb=rgb||'6,182,212';viz.classList.add('active');if(orb)orb.classList.add('pulse');let t=0,stopped=false,last=performance.now();function _follow(){if(_latestViz&&_latestViz!==viz){viz.classList.remove('active');if(orb)orb.classList.remove('pulse');viz=_latestViz;rgb=viz.dataset.rgb||rgb;orb=viz.querySelector('.viz-orb');const c2=viz.querySelector('canvas');if(c2)cx=c2.getContext('2d');viz.classList.add('active');if(orb)orb.classList.add('pulse');}}(function frame(){if(stopped)return;_vizAF=requestAnimationFrame(frame);_follow();const now=performance.now();t+=(now-last)/1000;last=now;const amp=_fakeAmp(t);_waveFrame(cx,W,H,rgb,t,amp);if(orb){orb.style.transform='scale('+(1+amp*.2)+')';orb.style.boxShadow='0 0 '+(6+amp*12)+'px rgba('+rgb+','+(.5+amp*.35)+')';}})();setTimeout(()=>{stopped=true;_vizStop();},30000);}

function _vizStart(audioEl){_vizStop();let viz=_latestViz;if(!viz)return;let rgb=viz.dataset.rgb||'6,182,212';let orb=viz.querySelector('.viz-orb'),cv=viz.querySelector('canvas'),cx=cv.getContext('2d');const W=cv.width,H=cv.height;function _attach(v){viz=v;rgb=v.dataset.rgb||rgb;orb=v.querySelector('.viz-orb');cv=v.querySelector('canvas');cx=cv.getContext('2d');v.classList.add('active');if(orb){orb.style.background='radial-gradient(circle at 35% 35%,rgba('+rgb+',.95),rgba('+rgb+',.55) 50%,rgba(5,5,20,.9))';orb.classList.add('pulse');}}function _follow(){if(_latestViz&&_latestViz!==viz){viz.classList.remove('active');const o=viz.querySelector('.viz-orb');if(o){o.classList.remove('pulse');o.style.transform='';o.style.boxShadow='';}_attach(_latestViz);}}_attach(viz);
let useAnalyser=false,buf=null;
// IMPORTANT: never route audio through Web Audio on iOS — createMediaElementSource reroutes the element's
// output through the AudioContext; if the ctx is suspended (or WebKit's MSE/blob silence bug hits) the TTS
// goes MUTE. iOS gets the procedural wave; desktop/Android get the real analyser only when ctx is running.
if(!_IOS){try{if(!_vizAudioCtx||_vizAudioCtx.state==='closed')_vizAudioCtx=new(window.AudioContext||window.webkitAudioContext)();if(_vizAudioCtx.state==='suspended'){try{_vizAudioCtx.resume();}catch(e){}}if(_vizAudioCtx.state==='running'){try{if(_vizSource)_vizSource.disconnect();}catch(e){}_vizSource=_vizAudioCtx.createMediaElementSource(audioEl);_vizAnalyser=_vizAudioCtx.createAnalyser();_vizAnalyser.fftSize=256;_vizAnalyser.smoothingTimeConstant=0.82;_vizSource.connect(_vizAnalyser);_vizAnalyser.connect(_vizAudioCtx.destination);buf=new Uint8Array(_vizAnalyser.frequencyBinCount);useAnalyser=true;}}catch(e){useAnalyser=false;}}
let stopped=false;audioEl.addEventListener('ended',()=>{stopped=true;_vizStop();},{once:true});
let t=0,flat=0,last=performance.now();
(function frame(){if(stopped)return;_vizAF=requestAnimationFrame(frame);_follow();const now=performance.now(),dt=(now-last)/1000;last=now;t+=dt;let amp;
if(useAnalyser){_vizAnalyser.getByteTimeDomainData(buf);let s=0;for(let i=0;i<buf.length;i++)s+=Math.abs(buf[i]-128);amp=s/buf.length/128;if(amp<0.004){flat+=dt;if(flat>0.9)useAnalyser=false;}else flat=0;
  if(useAnalyser){cx.clearRect(0,0,W,H);const g=cx.createLinearGradient(0,0,W,0);g.addColorStop(0,'rgba('+rgb+',0)');g.addColorStop(.5,'rgba('+rgb+',.9)');g.addColorStop(1,'rgba('+rgb+',0)');cx.strokeStyle=g;cx.lineWidth=1.8;cx.shadowBlur=5;cx.shadowColor='rgba('+rgb+',.7)';cx.beginPath();const sl=W/buf.length;for(let i=0;i<buf.length;i++){const y=(buf[i]/128)*H/2;i===0?cx.moveTo(0,y):cx.lineTo(i*sl,y);}cx.stroke();cx.shadowBlur=0;orb.style.transform='scale('+(1+amp*.25)+')';orb.style.boxShadow='0 0 '+(6+amp*14)+'px rgba('+rgb+','+(.5+amp*.4)+')';return;}}
amp=audioEl.paused&&!audioEl.ended?0.08:_fakeAmp(t);
_waveFrame(cx,W,H,rgb,t,amp);orb.style.transform='scale('+(1+amp*.25)+')';orb.style.boxShadow='0 0 '+(6+amp*14)+'px rgba('+rgb+','+(.5+amp*.4)+')';})();}

function _fireOnset(){const f=_onOnset;_onOnset=null;if(f){try{f();}catch(e){}}}

function _cueRGB(t){t=t||'';if(/\[Joke\]/i.test(t))return CUE_RGB.joke;if(/\[Watch me\]/i.test(t))return CUE_RGB.watch;if(/\[Try:/i.test(t))return CUE_RGB.try;if(/\[Probe/i.test(t))return CUE_RGB.probe;if(/\[Guess/i.test(t))return CUE_RGB.guess;if(/\[✓\]/.test(t))return CUE_RGB.check;if(/\[Notice/i.test(t))return CUE_RGB.notice;return '6,182,212';}

function _splitForTTS(t){t=(t||'').trim();const m=t.match(/^[\s\S]{12,160}?[.!?](?=\s)/);if(m)return[m[0].trim(),t.slice(m[0].length).trim()];const w=t.split(/\s+/);if(w.length>20)return[w.slice(0,14).join(' '),w.slice(14).join(' ')];return[t,''];}

function _oaiBody(text){const b={model:OAI_TTS_MODEL,input:text,voice:CHAR.key==='snake'?'fable':'echo',response_format:'mp3'};if(OAI_TTS_MODEL.indexOf('tts-1')===0){b.speed=CHAR.key==='snake'?.92:.97;}else{b.instructions='Speak warmly, clearly and a little slowly, like a friendly tutor talking to a young child.';}return b;}

function _oaiFetch(text){return fetch('https://api.openai.com/v1/audio/speech',{method:'POST',signal:_oaiController.signal,headers:{'Authorization':'Bearer '+OPENAI_KEY,'Content-Type':'application/json'},body:JSON.stringify(_oaiBody(text))});}

function _iosWarm(){try{if(window.speechSynthesis.speaking)return;const w=new SpeechSynthesisUtterance('\u00A0');w.volume=0.01;w.rate=16;window.speechSynthesis.speak(w);}catch(e){}}

function _warmAudio(){if(_audioWarmed)return;try{const a=new Audio('data:audio/wav;base64,UklGRigAAABXQVZFZm10IBIAAAABAAEARKwAAIhYAQACABAAAABkYXRhAgAAAAEA');a.volume=0;a.play().then(()=>{a.pause();_audioWarmed=true;}).catch(()=>{_audioWarmed=true;});}catch(e){_audioWarmed=true;}}

function cleanForSpeech(t){return t.replace(/_{3,}/g,'blank').replace(/_{1,2}/g,'').replace(/\*\*/g,'').replace(/\*/g,'').replace(/#{1,6}\s/g,'').replace(/\b(\d+)\s*%/g,'$1 percent').replace(/¾/g,'three quarters').replace(/½/g,'half').replace(/¼/g,'one quarter').trim();}

function classifyEngagement(text){
  const t=(text||'').trim().toLowerCase();
  if(!t)return 'disengaged';
  const tokens=t.split(/\s+/);
  if(/^(idk|dunno|dk|no\s*idea|don'?t\s*know|i\s*don'?t\s*know|i\s*dunno|nope|nah|na)$/.test(t))return 'disengaged';
  if(tokens.length===1 && /^(yes|no|ok|okay|sure|maybe|huh|what|um|hmm|err|uh|good|great|nice|cool|fine|yeah|yep)$/.test(t))return 'disengaged';
  return 'normal';
}

function renderBeatLabel(t){if(!t)return '';const e=s=>s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');return e(t).replace(/\[Joke\]/g,'<span class="beat-lbl beat-joke">[Joke]</span>').replace(/\[Watch me\]/g,'<span class="beat-lbl beat-watch">[Watch me]</span>').replace(/\[Try:([^\]]*?)\]/g,'<span class="beat-lbl beat-try">[Try:$1]</span>').replace(/\[✓\]/g,'<span class="beat-lbl beat-check">[✓]</span>').replace(/\[Notice:([^\]]*?)\]/g,'<span class="beat-lbl beat-notice">[Notice:$1]</span>').replace(/\[Probe:([^\]]*?)\]/g,'<span class="beat-lbl beat-probe">[Probe:$1]</span>').replace(/\[Probe\]/g,'<span class="beat-lbl beat-probe">[Probe]</span>').replace(/\[Guess:([^\]]*?)\]/g,'<span class="beat-lbl beat-guess">[Guess:$1]</span>').replace(/\[Guess\]/g,'<span class="beat-lbl beat-guess">[Guess]</span>').replace(/\*\*([^*]+?)\*\*/g,'<strong class="kw">$1</strong>');}

function showTyping(){const b=document.getElementById('ov-bubbles'),d=document.createElement('div');d.className='typing';d.id='typing-ind';d.innerHTML='<span></span><span></span><span></span>';b.appendChild(d);b.scrollTop=b.scrollHeight;}

function speakWebSpeech(text){
  try{if(window.speechSynthesis.paused)window.speechSynthesis.resume();}catch(e){}
  window.speechSynthesis.cancel();
  const myGen=++_speechGen;                         // generation stamp for this utterance
  setTimeout(()=>{
    if(myGen!==_speechGen)return;                   // hardStop() fired during 120ms — bail
    const u=new SpeechSynthesisUtterance(text);
    _currentUtt=u;
    if(_cachedVoice)u.voice=_cachedVoice;
    u.rate=CHAR.key==='snake'?.92:.98;
    u.pitch=CHAR.key==='snake'?.95:1.02;
    u.volume=1;
    u.onend=()=>{
      if(myGen!==_speechGen)return;                 // stale — another speak() took over
      _currentUtt=null;
      try{_vizStop();}catch(e){}
      try{const k=new SpeechSynthesisUtterance('\u00A0');k.volume=0.01;k.rate=16;window.speechSynthesis.speak(k);}catch(e){}
    };
    u.onerror=(ev)=>{
      if(myGen!==_speechGen)return;                 // cancelled by hardStop — NEVER retry
      if(ev?.error==='canceled'||ev?.error==='interrupted')return; // explicit cancel — ignore
      // genuine hardware error — fail silently, do not re-queue
    };
    window.speechSynthesis.speak(u);
    _fireOnset();
    if(_latestViz){const cv=_latestViz.querySelector('canvas');if(cv)_drawIdleViz(_latestViz,cv.getContext('2d'),cv.width,cv.height,_latestViz.querySelector('.viz-orb'),_latestViz.dataset.rgb);}
  },120);
}

async function speakOpenAI(text){try{_oaiController=new AbortController();
const MS=window.MediaSource||window.ManagedMediaSource; // ManagedMediaSource = iPhone Safari 17.1+; standard MediaSource = desktop/Android
if(MS&&MS.isTypeSupported&&MS.isTypeSupported('audio/mpeg')){
  // STREAMED playback: audio starts on the FIRST mp3 chunk — not after full synthesis.
  const resp=await _oaiFetch(text);
  if(resp.status===401){localStorage.removeItem('openai_key_v1');OPENAI_KEY=null;updateVoicePill();speakWebSpeech(text);return;}
  if(!resp.ok||!resp.body){speakWebSpeech(text);return;}
  const ms=new MS();_oaiAudio=new Audio();if(window.ManagedMediaSource&&MS===window.ManagedMediaSource)_oaiAudio.disableRemotePlayback=true; // mandatory for MMS
  _oaiObjectUrl=URL.createObjectURL(ms);_oaiAudio.src=_oaiObjectUrl;_oaiAudio.onended=()=>{if(_oaiObjectUrl){URL.revokeObjectURL(_oaiObjectUrl);_oaiObjectUrl=null;}_oaiAudio=null;};
  await new Promise(res=>ms.addEventListener('sourceopen',res,{once:true}));
  const sb=ms.addSourceBuffer('audio/mpeg');const reader=resp.body.getReader();let started=false;
  const pump=async()=>{try{const{done,value}=await reader.read();if(done){try{ms.endOfStream();}catch(e){}return;}await new Promise(res=>{sb.addEventListener('updateend',res,{once:true});sb.appendBuffer(value);});if(!started){started=true;_oaiAudio.play().then(()=>{_fireOnset();_vizStart(_oaiAudio);}).catch(()=>{try{_oaiController.abort();}catch(e){}if(_oaiAudio){_oaiAudio.src='';_oaiAudio=null;}speakWebSpeech(text);});}pump();}catch(e){}};
  pump();
}else{
  // No MediaSource at all (older iOS): PIPELINE two short requests — sentence 1 plays while the rest synthesises in parallel.
  const parts=_splitForTTS(text);
  const r1p=_oaiFetch(parts[0]);
  const b2p=parts[1]?_oaiFetch(parts[1]).then(r=>r.ok?r.blob():null).catch(()=>null):null;
  const r1=await r1p;
  if(r1.status===401){localStorage.removeItem('openai_key_v1');OPENAI_KEY=null;updateVoicePill();speakWebSpeech(text);return;}
  if(!r1.ok){speakWebSpeech(text);return;}
  const b1=await r1.blob();
  _oaiObjectUrl=URL.createObjectURL(b1);_oaiAudio=new Audio(_oaiObjectUrl);const a1=_oaiAudio;
  a1.onended=async()=>{if(_oaiAudio!==a1)return; // hardStop() took over
    if(_oaiObjectUrl){URL.revokeObjectURL(_oaiObjectUrl);_oaiObjectUrl=null;}
    if(!b2p){_oaiAudio=null;return;}
    try{const b2=await b2p;if(!b2||_oaiAudio!==a1)return;
      _oaiObjectUrl=URL.createObjectURL(b2);const a2=new Audio(_oaiObjectUrl);_oaiAudio=a2;
      a2.onended=()=>{if(_oaiObjectUrl){URL.revokeObjectURL(_oaiObjectUrl);_oaiObjectUrl=null;}_oaiAudio=null;_vizStop();};
      await a2.play();_vizStart(a2);
    }catch(e){}};
  try{await a1.play();}catch(pe){_oaiAudio=null;speakWebSpeech(text);return;}
  _fireOnset();_vizStart(a1);
}}catch(e){if(e.name!=='AbortError')speakWebSpeech(text);}}

async function speak(text){if(!text)return;const c=cleanForSpeech(text);hardStop();if(OPENAI_KEY){await speakOpenAI(c);}else{speakWebSpeech(c);}}

function hardStop(){
  _onOnset=null;try{_vizStop();}catch(e){}
  if(_streamCancel){const fn=_streamCancel;_streamCancel=null;fn();}
  _speechGen++;                                     // invalidate all pending speakWebSpeech callbacks
  if(_currentUtt){_currentUtt.onend=null;_currentUtt.onerror=null;_currentUtt=null;} // null handlers before cancel
  if(_oaiController){_oaiController.abort();_oaiController=null;}
  if(_oaiAudio){_oaiAudio.pause();_oaiAudio.src='';_oaiAudio=null;}
  if(_oaiObjectUrl){URL.revokeObjectURL(_oaiObjectUrl);_oaiObjectUrl=null;}
  try{window.speechSynthesis.pause();}catch(e){}
  try{window.speechSynthesis.cancel();}catch(e){}
}

function addBubble(text,role){const b=document.getElementById('ov-bubbles'),d=document.createElement('div');d.className='bub '+role;if(role==='echo'){const rgb=_cueRGB(text);d.style.setProperty('--kw','rgb('+rgb+')');d.innerHTML=renderBeatLabel(text);const viz=document.createElement('div');viz.className='echo-viz';viz.dataset.rgb=rgb;viz.innerHTML='<div class="viz-orb"></div><canvas width="150" height="22"></canvas>';d.appendChild(viz);_latestViz=viz;}else{d.textContent=text;}b.appendChild(d);b.scrollTop=b.scrollHeight;}

function streamEchoGrouped(raw){
  const b=document.getElementById('ov-bubbles');
  const lines=(raw||'').split(/\n+/).map(s=>s.trim()).filter(Boolean);
  let groups=[];
  lines.forEach(ln=>{const idx=ln.indexOf('|||');let sp,dp;if(idx>=0){sp=ln.slice(0,idx).trim();dp=ln.slice(idx+3).trim();}else{sp=ln;dp='';}if(!sp)return;
    if(!dp){const parts=sp.replace(/[*_`]/g,'').split(/\s+/);dp=parts.slice(0,8).join(' ')+(parts.length>8?'…':'');} // never dump the transcript / never a bare label
    groups.push({sp:sp,dp:dp});});
  if(!groups.length){const parts=(raw||'').split(/\s+/);groups.push({sp:raw||'',dp:parts.slice(0,8).join(' ')+(parts.length>8?'…':'')});}
  groups=groups.filter((g,i)=>i===0||g.dp!==groups[i-1].dp); // drop back-to-back identical cues
  const fullSpoken=groups.map(g=>g.sp).join(' ').replace(/\*+/g,'');
  speak(fullSpoken);
  setInputDisabled(true);
  const wc=g=>((g.sp.match(/\S+/g)||[]).length||1);
  const totalWords=groups.reduce((a,g)=>a+wc(g),0)||1;
  const baseWpm=OPENAI_KEY?(CHAR.key==='snake'?150:160):165;
  const totalMs=(totalWords/baseWpm)*60000;
  let acc=0;const starts=groups.map(g=>{const s=(acc/totalWords)*totalMs;acc+=wc(g);return s;});
  let shown=0,timeoutId=null,startAt=0,begun=false;
  function complete(){if(timeoutId)clearTimeout(timeoutId);while(shown<groups.length){addBubble(groups[shown].dp,'echo');shown++;}setInputDisabled(false);_streamCancel=null;_onOnset=null;b.scrollTop=b.scrollHeight;}
  _streamCancel=complete;
  function step(){if(_streamCancel!==complete)return;const elapsed=performance.now()-startAt;while(shown<groups.length&&elapsed>=starts[shown]){addBubble(groups[shown].dp,'echo');shown++;b.scrollTop=b.scrollHeight;}if(shown<groups.length)timeoutId=setTimeout(step,80);else timeoutId=setTimeout(complete,Math.max(0,totalMs-elapsed)+200);}
  function begin(){if(begun||_streamCancel!==complete)return;begun=true;removeTyping();startAt=performance.now();step();}
  _onOnset=begin;                         // reveal text exactly when audio starts (keeps "thinking…" up until then)
  timeoutId=setTimeout(begin,3500);       // fail-safe: reveal anyway if audio never fires
}
